### ISSUE TITLE
Comments in the posts

### ISSUE THREAD

**Issue by grojar** [jmau111/hugo-theme-ava#3]
Hi J., thank you very much for sharing this theme...it's awesome.

i'd be very pleased if you can add disqus or other comments in the posts...

Best regards!!

**Comment by jmau111** [comment]
nice suggestion, Sorry for the delay :(

**Comment by jmau111** [comment]
I've added an option in Site params called `disqus`.

**Comment by grojar** [comment]
Thank you very much for including it!!

I've replaced the code in the file disqus.html with this one taken from hugo webpage (https://gohugo.io/templates/internal#conditional-loading-of-disqus-comments)

It worked in this webpage (Ava theme is suuuper, thanks again)
https://grojar.github.io/Petrofisica-en-Python/
