### ISSUE TITLE
Typos in README

### ISSUE THREAD

**Issue by flbrack** [jmau111/hugo-theme-ava#4]
Hi,
Firstly, nice theme! 

I was trying it out, and noticed in the README section on cloning the git repo, it says 
`
git clone https://github.com/jmau111/hugo-theme-ava.git themes/hugo-themes-ava
`
but I think it should be 
`
git clone https://github.com/jmau111/hugo-theme-ava.git themes/hugo-theme-ava
`
 as it did not run until I renamed the folder.

Also, after copying the example site, and running `hugo server`, it opens on `localhost:1313/hugo-theme-ava` instead of just `localhost:1313`, which I was able to fix by changing the config.toml.

Thanks and all the best!

**Comment by jmau111** [comment]
Oh crap, I'll look into it. Thanks for reporting!
