### ISSUE TITLE
subheader background-image

### ISSUE THREAD

**Issue by grojar** [jmau111/hugo-theme-ava#5]
hi Julien, thank you for sharing with us this breathtaking theme.

i had some issues trying to get the correct url for background images.. 

i added  absURL  to  background-image's url in subheader.html file. It worked for me.

url({{ .context.Params.image | default .site.Params.meta_tags.meta_og_image **| absURL** }})

all the best,

Pablo

**Comment by jmau111** [comment]
thanks for reporting. I'll check it.
